### ISSUE TITLE
Edit scarlet tutorial for DESC+DC2

### ISSUE THREAD

**Issue by yymao** [LSSTDESC/StackClub#1]
I'll push my edited scarlet tutorial ([original](https://github.com/LSSTScienceCollaborations/StackClub/blob/master/Deblending/scarlet_tutorial.ipynb)) that works in DESC env and with DC2 DR6 data to this repo. 

@herjy I'll let you know when it's here, and it would be great to have you review it!

**Comment by herjy** [comment]
Sure! Thanks @yymao I might make a few edits to the notebook for the purpose of the demo.
